FROM golang:1.19

WORKDIR /app

# Copy the source code from the host machine to the container
COPY . .

WORKDIR /app/cmd/all

# Build the executable
RUN go build -o /app/cronnyapi

WORKDIR /app/src/

ENV USE_PG="yes"

# Set the command to run the executable
CMD ["sh", "-c", "USE_PG=yes /app/cronnyapi"]
